# This is to use docker in development, so you don't have to specify port mapping and volumes every time you run docker
version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
