sudo: required
services:
- docker
before_install:
- docker build -t eleroy7/movie-site-frontend -f ./frontend/Dockerfile.dev ./frontend
script:
- docker run eleroy7/movie-site-frontend npm run test -- --coverage
deploy:
  provider: heroku
  api_key:
    secure: QpnXc1Vkevq0t4LMaWzGR9gS9xD5DPZruC1nU+jI0cRcEwEcSxUDQb3B4qbm+4N8l7hRP2Zzj9q4SOsVA34ug9Iw4JUkvqZMABCeT2VbaUg9J4EEjei3pdCC/dhX2eaiN9IXYzSh/6YaMDHwsnHFSP68yI74sZCrgGMjmzPf01kcouA+jVFiAJ3POc41tbpXftek+4doDTcQxckvG5aMXcUvirZIlOVdddSz1qxioG3RPHxL0ink9GKmbSZ3Byvhcq/Gw85u0yvu1hqkL4F5u4nqfUUZAMIM9upbOkn108omx7xTzytOeeB5LzTV8acyjXbKBBEuUZxcfk9Q94gMVZBen30cXuJI3RbwhPWFVXxl8s1f3AWRyJi/s5a/gycH/Od99Y2+1i23ZLcb5iJWoaS/tkH2Nxtqww0/VPQeMlrxqaS7TY/EdXniPotoOd1qYkORvCOxJRptVrbNhs/4/wGVNiRGh8gxtSbkVwdlgdAWxCYEQFKeSLrA2m1+kYa44xMRZhjwr3GDxjQdNwqwaGt9zgncGodu1LLwlfwppcD/SRdmTZ/Soq04qz+Zoi+l14bnhT/PzXNiW1637eKAkBAGOT/n1NIvGMAkHtuG4LlLFg2OMmOLtyql6wT36HF2G0+xM0VZBSE/gBHiNhZZfq2EoZiIlIITggvWzwwGNzg=
  app: movie-site1
  on:
    repo: Redhairedgadget/movie-site
