export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_MOVIES = 'SET_MOVIES';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';

export const SET_OPTION = 'SET_OPTION';

export const ADD_REMOVE_BOOKMARK = 'ADD_REMOVE_BOOKMARK';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const SET_USER_BOOKMARKS = 'SET_USER_BOOKMARKS';